[game]
hostname = "[EN] Lizard Loose 14"
panic_bunker.enabled = false
panic_bunker.disable_with_admins = false
panic_bunker.enable_without_admins = false
panic_bunker.custom_reason = ""
desc             = "Slop or flop. You decide!"
lobbyenabled     = true
soft_max_players = 80
lobbyduration    = 300
role_timers      = false
role_loadout_timers = false
map_pool         = "UMMapPool"
secret_weight_prototype = "UMSecret"

[shuttle]
emergency_early_launch_allowed = true

[movement]
mob_pushing = false

[net]
max_connections = 1024

[vote]
restart_required_ratio = 0.7

[netres]
limit = 10.0

[admin]
see_own_notes = true
deadmin_on_join = true
new_player_threshold = 600
alert.min_players_sharing_connection = 2
allow_multi_server_play = false

[hub]
tags = "lang:en,region:am_n_w,rp:low"

[audio]
attenuation = 4 # inversedistanceclamped 1 << 2, see audioparams.cs
z_offset = -2

[ambience]
range = 15# APCs
