using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._UM.Ghost.UI;

[GenerateTypedNameReferences]
public sealed partial class UMGhostWarpCategory : Control
{
    public UMGhostWarpCategory()
    {
        RobustXamlLoader.Load(this);

        Heading.StyleClasses.Add("OpenLeft");
    }

    [ViewVariables]
    public string? Text
    {
        get => Heading.Label.Text;
        set => Heading.Label.Text = value;
    }

    public WrapContainer.ItemJustification Justification
    {
        get => ButtonContainer.Justification;
        set => ButtonContainer.Justification = value;
    }

    public void AddButton(Control child)
    {
        Collapsible.Visible = true;
        ButtonContainer.AddChild(child);
    }

    public OrderedChildCollection GetButtons()
    {
        return ButtonContainer.Children;
    }

}

