using System.Linq;
using System.Numerics;
using Content.Shared._UM.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._UM.Ghost.UI;

[GenerateTypedNameReferences]
public sealed partial class UMGhostWarpWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private List<UMPlayerWarp> _playerWarps = new();
    private List<UMLocationWarp> _locationWarps = new();

    private string _searchText = string.Empty;

    public event Action<NetEntity>? WarpClicked;

    public event Action? OnGhostnadoClicked;

    public UMGhostWarpWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchBar.OnTextChanged += OnSearchTextChanged;
        GhostnadoButton.OnPressed += _ => OnGhostnadoClicked?.Invoke();
    }

    public void UpdateWarps(IEnumerable<UMPlayerWarp> playerWarps, IEnumerable<UMLocationWarp> locationWarps)
    {
        _playerWarps = playerWarps.OrderByDescending(warp =>
            {
                if (warp.Job == null)
                    return 0;

                if (_prototype.TryIndex(warp.Job, out var jobProto))
                    return jobProto.RealDisplayWeight;

                return 0;

            })
            .ToList();

        _locationWarps = locationWarps.ToList();
    }

    public void Populate()
    {
        LocationButtons.RemoveAllChildren();
        PlayerButtons.RemoveAllChildren();
        AntagonistButtons.RemoveAllChildren();
        AddButtons();
    }

    private void AddButtons()
    {
        foreach (var warp in _playerWarps)
        {
             var currentButtonRef = new UMPlayerButton();
             currentButtonRef.Populate(warp.Name, warp.Job);

            currentButtonRef.OnPressed += _ => WarpClicked?.Invoke(warp.Entity);
            currentButtonRef.Visible = ButtonIsVisible(currentButtonRef);

            if (warp.Antagonist)
            {
                AntagonistButtons.AddChild(currentButtonRef);
                continue;
            }
            PlayerButtons.AddChild(currentButtonRef);
        }

        foreach (var warp in _locationWarps)
        {
            var currentButtonRef = new Button
            {
                Text = warp.Name,
                TextAlign = Label.AlignMode.Center,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                SizeFlagsStretchRatio = 1,
                ClipText = false,
            };

            currentButtonRef.OnPressed += _ => WarpClicked?.Invoke(warp.Entity);
            currentButtonRef.Visible = ButtonIsVisible(currentButtonRef);

            LocationButtons.AddChild(currentButtonRef);
        }
    }

    private bool ButtonIsVisible(Button button)
    {
        return string.IsNullOrEmpty(_searchText) || button.Text == null || button.Text.Contains(_searchText, StringComparison.OrdinalIgnoreCase);
    }

    private bool PlayerButtonIsVisible(UMPlayerButton button)
    {
        return string.IsNullOrEmpty(_searchText) || button.PlayerName.Text == null || button.PlayerName.Text.Contains(_searchText, StringComparison.OrdinalIgnoreCase);
    }

    private void UpdateVisibleButtons()
    {
        foreach (var child in LocationButtons.Children)
        {
            if (child is Button button)
                button.Visible = ButtonIsVisible(button);
        }
        foreach (var child in PlayerButtons.Children)
        {
            if (child is UMPlayerButton button)
                button.Visible = PlayerButtonIsVisible(button);
        }
        foreach (var child in AntagonistButtons.Children)
        {
            if (child is UMPlayerButton button)
                button.Visible = PlayerButtonIsVisible(button);
        }
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _searchText = args.Text;

        UpdateVisibleButtons();
        // Reset scroll bar so they can see the relevant results.
        GhostScroll.SetScrollValue(Vector2.Zero);
    }
}

