using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._UM.Ghost.UI;

[GenerateTypedNameReferences]
public sealed partial class UMPlayerButton : Button
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    private readonly SpriteSystem _sprite;
    public int Weight = 0;

    public UMPlayerButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entityManager.System<SpriteSystem>();
    }

    public void Populate(string name, ProtoId<JobPrototype>? job)
    {
        if (_prototype.TryIndex(job, out var jobPrototype))
        {
            JobIcon.Texture = _sprite.Frame0(_prototype.Index(jobPrototype.Icon).Icon);
            JobIcon.ToolTip = jobPrototype.LocalizedName;
            Weight = jobPrototype.RealDisplayWeight;
        }

        PlayerName.Text = name;

    }

}

