using Content.Client.RichText;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._UM.News.UI;

[GenerateTypedNameReferences]
public sealed partial class NewscasterEntry : Control
{
    public NewscasterEntry(string title, string? author, string contents, TimeSpan publishTime)
    {
        RobustXamlLoader.Load(this);

        Title.Text = title;

        if (author != null)
        {
            var authorText = Loc.GetString("newscaster-publish-author", ("author", author));
            Author.Text = authorText;
        }

        ArticleContents.SetMessage(FormattedMessage.FromMarkupPermissive(contents), UserFormattableTags.BaseAllowedTags);

        var timeText = Loc.GetString("newscaster-publish-time", ("time", publishTime.ToString("hh\\:mm\\:ss")));
        Time.Text = timeText;
    }
}

