using Content.Client.UserInterface.Controls;
using Content.Shared.MassMedia.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._UM.News.UI;

[GenerateTypedNameReferences]
public sealed partial class NewscasterWindow : FancyWindow
{
    public NewscasterWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void OpenWindow()
    {
        NoArticleText.Visible = true;
    }

    public void UpdateState(List<NewsArticle> articles)
    {
        EntryTable.RemoveAllChildren();

        if (articles.Count == 0)
        {
            NoArticleText.Visible = true;
            return;
        }
        NoArticleText.Visible = false;
        articles.Reverse();
        foreach (var article in articles)
        {
            AddEntry(article.Title, article.Author, article.Content, article.ShareTime);
        }
    }

    public void AddEntry(string title, string? author, string contents, TimeSpan publishTime)
    {
        var entry = new NewscasterEntry(title, author, contents, publishTime);
        EntryTable.AddChild(entry);
    }
}

