using Content.Shared._UM.Cargo.Components;
using Content.Shared.Shuttles.Systems;
using Content.Shared.Timing;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._UM.Cargo.UI;

[GenerateTypedNameReferences]
public sealed partial class UMCargoShuttleWindow : DefaultWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IEntityManager _entManager = default!;

    public event Action? OnSendButton;

    private StartEndTime? _startEndTime;

    public UMCargoShuttleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        SendButton.OnPressed += _ => OnSendButton?.Invoke();
    }

    public void UpdateState(UMCargoShuttleBoundUserInterfaceState state)
    {
        _startEndTime = state.StateTime;

        if (!_entManager.TryGetEntity(state.Location, out var locationEnt))
            LocationLabel.Text = "unknown";

        if (_entManager.TryGetComponent<MetaDataComponent>(locationEnt, out var meta))
            LocationLabel.Text = "Location:  " + meta.EntityName;

        var statusText = Loc.GetString($"shuttle-console-ftl-state-{state.FTLState.ToString()}");

        StatusLabel.Text = "Status:  " + statusText;

        if (state.FTLState == FTLState.Available)
        {
            SendButton.Disabled = false;
            return;
        }
        SendButton.Disabled = true;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateCountdown();
    }

    private void UpdateCountdown()
    {
        if (_startEndTime == null)
        {
            Countdown.Text = "Ready!";
            return;
        }

        if (_startEndTime.Value.End < _timing.CurTime)
        {
            Countdown.Text = "Time Remaining: 00:00:00";
            return;
        }

        var timeLeft = _startEndTime.Value.End - _timing.CurTime;
        var timestring = timeLeft.ToString(@"hh\:mm\:ss");
        Countdown.Text = "Time Remaining: " + timestring;
    }
}

