using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._UM.Drip.UI;

[GenerateTypedNameReferences]
public sealed partial class DripDrobeWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IGameTiming _timing = default!;

    public event Action<BaseButton.ButtonEventArgs, string>? OnItemSelected;

    private Dictionary<EntProtoId, int> _cachedListings = new();
    private Dictionary<EntProtoId, DripDrobeEntry> _buttons = new();

    public DripDrobeWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

    }

    private void CreateItem(string item, int amount)
    {
        if (!_prototypeManager.TryIndex(item, out var prototype))
            return;

        _cachedListings.Add(item, amount);

        var entry = new DripDrobeEntry(prototype, prototype.Name, prototype.Description, amount);

        _buttons.Add(item, entry);
        ProgramList.AddChild(entry);

        entry.ItemRedeemButton.OnPressed += args =>
        {
            UpdateListing(item);
            OnItemSelected?.Invoke(args, item);
        };
    }

    public void UpdateListing(string itemId)
    {
        if (!_buttons.TryGetValue(itemId, out var entry))
            return;

        if (!_cachedListings.TryGetValue(itemId, out var stock))
            return;

        if (!_timing.IsFirstTimePredicted)
            return;

        _cachedListings[itemId] = Math.Max(stock - 1, 0);
        entry.SetStock(_cachedListings[itemId]);
    }

    public void Populate(IReadOnlyDictionary<string, int> items)
    {
        _cachedListings = new Dictionary<EntProtoId, int>();
        _buttons = new Dictionary<EntProtoId, DripDrobeEntry>();

        foreach (var item in items)
        {
            if (item.Value == 0)
                continue;

            CreateItem(item.Key, item.Value);
        }
        //VendingContents.PopulateList(listData);
    }
}

