using System.Text.RegularExpressions;
using Content.Shared.Chat;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._UM.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class FancySpeechBubble : Control
{
    public int WordWrapLength = 32;

    private int _fontSize;
    private string _font;
    private Color? _color;

    public FancySpeechBubble(ChatMessage message, int fontSize = 24, string font = "TinyUnicode", Color? fontColor = null)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _color = fontColor;
        _fontSize = fontSize;
        _font = font;

        BuildLines(message, "BubbleContent");
    }

    public static (string? FontName, int? FontSize) ParseFont(string input)
    {
        var match = Regex.Match(input, @"\[font=([^\s\]]+)\s+size=(\d+)\]", RegexOptions.IgnoreCase);

        if (match.Success)
        {
            string fontName = match.Groups[1].Value;
            int fontSize = int.Parse(match.Groups[2].Value);
            return (fontName, fontSize);
        }
        return (null, null);
    }

    public void BuildLines(ChatMessage chatMessage, string tag)
    {
        var messageString = SharedChatSystem.GetStringInsideTag(chatMessage, tag);
        var font = ParseFont(chatMessage.WrappedMessage);

        if (font.FontName != null)
            _font = font.FontName;

        if (font.FontSize != null)
            _fontSize = font.FontSize.Value;

        var wrappedText = WordWrapHelper.Wordwrap(messageString, 32);

        foreach (var message in wrappedText)
        {
            var msg = new FormattedMessage();

            msg.PushTag(new MarkupNode("font",
                new MarkupParameter(_font),
                new Dictionary<string, MarkupParameter>()
                {
                    { "size", new MarkupParameter(_fontSize) }
                }));


            if (_color != null)
                msg.PushColor(_color.Value);

            msg.AddMarkupOrThrow(message);
            msg.Pop();
            msg.Pop();

            var label = new OutlineRichTextLabel
            {
                Thickness = _fontSize / 6,
                StyleClasses = { "bubbleContent" },
                HorizontalAlignment = HAlignment.Center
            };

            label.SetMessage(msg, tagsAllowed: [ typeof(FontTag), typeof(ColorTag), typeof(ItalicTag), typeof(BoldTag) ]);

            var labelContainer = new BoxContainer
            {
                Align = BoxContainer.AlignMode.Center
            };

            labelContainer.AddChild(label);
            TextContainer.AddChild(labelContainer);
        }
    }

}

