using System.Linq;
using System.Numerics;
using System.Text.RegularExpressions;
using Content.Shared.Chat;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._UM.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class FancySpeechBubble : Control
{
    public int WordWrapLength = 32;

    private int _fontSize;
    private string _font;
    private Color? _color;
    private bool _forceFont;
    private int? _thicknessOverride;
    private string? _contentTag;
    private string? _glyph;

    public FancySpeechBubble(ChatMessage message, int fontSize = 12, string font = "Minecraft", bool forceFont = false, Color? fontColor = null, int? thicknessOverride = null, string? contentTag = null, string? glyph = null)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _color = fontColor;
        _fontSize = fontSize;
        _font = font;
        _forceFont = forceFont;
        _thicknessOverride = thicknessOverride;
        _contentTag = contentTag;
        _glyph = glyph;

        BuildLines(message, _contentTag);
    }

    /// <summary>
    /// Gets the font that the message has.
    /// </summary>
    /// <param name="message"></param>
    private (string? FontName, int? FontSize) ParseFont(string input)
    {
        var match = Regex.Match(input, @"\[font=([^\s\]]+)\s+size=(\d+)\]", RegexOptions.IgnoreCase);

        if (match.Success)
        {
            string fontName = match.Groups[1].Value;
            int fontSize = int.Parse(match.Groups[2].Value);
            return (fontName, fontSize);
        }
        return (null, null);
    }


    private void BuildLines(ChatMessage chatMessage, string? tag)
    {
        string messageString;
        if (tag != null)
        {
            messageString = SharedChatSystem.GetStringInsideTag(chatMessage, tag);
        }
        else
        {
            messageString = chatMessage.WrappedMessage;
        }

        var glyphed = false;

        var font = ParseFont(chatMessage.WrappedMessage);

        if (font.FontName != null && !_forceFont)
            _font = font.FontName;

        if (font.FontSize != null && !_forceFont)
            _fontSize = font.FontSize.Value;

        var wraptest = WordWrapHelper.WordWrap(messageString, WordWrapLength);

        foreach (var message in wraptest)
        {
            Log.Debug("message: " + message);

            var msg = new FormattedMessage();

            msg.PushTag(new MarkupNode("font",
                new MarkupParameter(_font),
                new Dictionary<string, MarkupParameter>()
                {
                    { "size", new MarkupParameter(_fontSize) }
                }));
            if (_color != null)
                msg.PushColor(_color.Value);

            msg.AddMarkupOrThrow(message);
            msg.Pop();
            msg.Pop();

            var thickness = _fontSize / 6;

            if (_thicknessOverride != null)
                thickness = _thicknessOverride.Value;

            var label = new OutlineRichTextLabel
            {
                Thickness = thickness,
                StyleClasses = { "bubbleContent" },
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(thickness * 3),
            };
            label.SetMessage(msg, tagsAllowed: [ typeof(FontTag), typeof(ColorTag), typeof(BoldTag) ]);

            var labelContainer = new BoxContainer
            {
                Align = BoxContainer.AlignMode.Center,
                VerticalAlignment = VAlignment.Center,
            };

            if (_glyph != null && !glyphed)
            {
                var textureRect = new TextureRect
                {
                    TexturePath = _glyph,
                    TextureScale = new Vector2(2, 2),
                };

                labelContainer.AddChild(textureRect);
                glyphed = true;
            }


            labelContainer.AddChild(label);
            TextContainer.AddChild(labelContainer);

        }
    }

    /// <summary>
    /// Where the barely working magic happens
    /// </summary>
    /// <param name="message"></param>
    /// <returns></returns>
    private List<FormattedMessage> BuildMessages(FormattedMessage message)
    {
        List<FormattedMessage> lines = new();

        List<MarkupNode> unclosedNodes = new();

        FormattedMessage currentLine = new();

        var wrapLimit = 35;

        foreach (var node in message)
        {
            //There is text in this node
            if (node.Name == null && node.Value.StringValue != null)
            {
                foreach (var tag in unclosedNodes)
                {
                    currentLine.PushTag(tag);
                }

                if (currentLine.ToString().Length + node.Value.StringValue.Length < wrapLimit)
                {
                    currentLine.PushTag(node);
                    continue;
                }

                if (currentLine.ToString().Length + node.Value.StringValue.Length >= wrapLimit)
                {
                    //var wrapList = ShittyWrap(node.Value.StringValue, wrapLimit);
                    var wrapList = WordWrapHelper.WordWrap(node.Value.StringValue, wrapLimit);

                    foreach (var wrap in wrapList)
                    {
                        if (currentLine.ToString().Length + wrap.Length <= wrapLimit + (wrapLimit / 4))
                        {
                            currentLine.AddMarkupOrThrow(wrap);
                            continue;
                        }

                        var newLine = new FormattedMessage();
                        foreach (var tag in unclosedNodes)
                        {
                            currentLine.Pop();
                            newLine.PushTag(tag);
                        }
                        lines.Add(currentLine);
                        currentLine = newLine;
                        currentLine.AddMarkupOrThrow(wrap);
                        foreach (var _ in unclosedNodes)
                        {
                            currentLine.Pop();
                        }
                    }
                }
                continue;
            }
            //This node is a tag we've already seen
            if (node.Closing)
            {
                currentLine.Pop();
                var toRemove = unclosedNodes.FindLast(n => node.Name == n.Name);
                if (toRemove != null)
                    unclosedNodes.Remove(toRemove);
                continue;
            }

            //This node is a tag
            if (node.Name != null && !node.Closing)
            {
                unclosedNodes.Add(node);
                continue;
            }
        }

        if (currentLine.Count > 0)
        {
            lines.Add(currentLine);

        }

        return lines;
    }

}

