using System.Linq;
using System.Numerics;
using Content.Shared.Chat;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._UM.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class FancySpeechBubble : Control
{
    public int WordWrapLength = 32;

    private int _fontSize;
    private string _font;
    private Color? _color;

    public FancySpeechBubble(ChatMessage message, int fontSize = 12, string font = "Grand9K", Color? fontColor = null)
    {
        RobustXamlLoader.Load(this);

        _color = fontColor;
        _fontSize = fontSize;
        _font = font;

        BuildLines(message, "BubbleContent");
    }

    static IEnumerable<string> Split(string str, int chunkSize)
    {
        return Enumerable.Range(0, str.Length / chunkSize)
            .Select(i => str.Substring(i * chunkSize, chunkSize));
    }

    private List<String> WrapWords(string message)
    {
        var messages = new List<string>();

        if (message.Length <= WordWrapLength)
        {
            messages.Add(message);
            return messages;
        }

        var split = Split(message, WordWrapLength);
        foreach (var part in split)
        {
            messages.Add(part);
        }

        return messages;
    }

    public void BuildLines(ChatMessage chatMessage, string tag)
    {
        var messageString = SharedChatSystem.GetStringInsideTag(chatMessage, tag);

        var messageLines = WrapWords(messageString);

        foreach (var message in messageLines)
        {
            var msg = new FormattedMessage();

            //this fucking sucks I hate this shit
            msg.PushTag(new MarkupNode("font",
                new MarkupParameter(_font),
                new Dictionary<string, MarkupParameter>()
                {
                    {"size", new MarkupParameter(_fontSize)}
                }));

            if (_color != null)
                msg.PushColor(_color.Value);
            msg.AddText(message);
            msg.Pop();
            msg.Pop();

            var label = new OutlineRichTextLabel
            {
                Margin = new Thickness(0, 0, 0, 0),
                StyleClasses = { "bubbleContent" },
                HorizontalAlignment = HAlignment.Center
            };

            label.SetMessage(msg, tagsAllowed: [ typeof(FontTag), typeof(ColorTag), typeof(ItalicTag) ]);

            var labelContainer = new BoxContainer
            {
                Margin = new Thickness(5),
                Align = BoxContainer.AlignMode.Center
            };

            labelContainer.AddChild(label);


            TextContainer.AddChild(labelContainer);
        }
    }

}

