using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._UM.Antags.Victim.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._UM.Antags.Victim;

[GenerateTypedNameReferences]
public sealed partial class VictimTimerGui : Control
{
    [Dependency] private readonly IGameTiming _gameTiming = default!;

    public bool IsOpen => Parent != null;

    private TimeSpan _detonationTime;

    public VictimTimerGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }


    protected override void FrameUpdate(FrameEventArgs args)
    {
        RecenterWindow(new Vector2(0.6f, 0.06f));
        UpdateTimer();
    }

    public void Update(TimeSpan detonationTime)
    {
        _detonationTime = detonationTime;
    }

    public void Open()
    {
        if (!Visible)
        {
            Visible = true;
        }

        if (!IsOpen)
        {
            UserInterfaceManager.WindowRoot.AddChild(this);
        }
    }

    public void OpenCenteredAt(Vector2 relativePosition)
    {
        Measure(Vector2Helpers.Infinity);
        Open();
        RecenterWindow(relativePosition);
    }

    public void RecenterWindow(Vector2 relativePosition)
    {
        if (Parent == null)
            return;

        // Where we want the upper left corner of the window to be
        var corner = Parent!.Size * Vector2.Clamp(relativePosition, Vector2.Zero, Vector2.One) - DesiredSize / 2;

        // Attempt to keep the whole window is visible, regardless of the target position. e.g., if the target for
        // the center is (0,0), this will actually open the window so that the upper left is at (0,0). If the window
        // is bigger than the parent, this will currently prioritize showing the upper left corner.
        var pos = Vector2.Clamp(corner, Vector2.Zero, Parent.Size - DesiredSize);
        LayoutContainer.SetPosition(this, pos);
    }

    private void UpdateTimer()
    {
        var timeLeft = _gameTiming.CurTime.Subtract(_detonationTime);
        CountdownTimer.Text = "[font=\"AnimalSilence\" size=40]" + timeLeft.ToString("mm\\:ss") + "[/font]";
    }
}

